### ISSUE TITLE
Pro micro completely unrecognised by windows machine.

### ISSUE THREAD

**Issue by Gazza2000** [MakotoKurauchi/helix#27]
Hi, I recently was able to flash my Helix halves with LED testing firmware as I was building it. Once each half was flashed, I had about a month of not flashing them as bit-by-bit I finished the build. (Note: I have never flashed both halves when they were connected.) I continued building and finally had them complete and connected both halves for the first time in a long time, but did not flash them. I proceeded to plug each half in at a time with the intention of flashing them with useful firmware other than the LED test firmware so that I may finally type with it. The two windows machines that I have tried on do not recognise the presence of either halves neither in QMK Toolbox nor in Device Manager. I am not getting the chimes as you would usually get when plugging or unplugging a USB device, and the reset button hasn't made made a difference either. Also, interestingly, if a Helix module is plugged in, it receives power and the OLED and LED presets work and I can cycle through them as expected, however this continues even when my windows machines are asleep or even shut down but still powered ! (I noted that this does not happen if the computer had not been booted but is shut down and powered) This behavior is similar to the LED's on my motherboard which stay on when the machine is shut down etc. 
I have tried communicating with the pro micro using Arduino IDE but it was still undetectable and I didn't have any new ideas.
Someone mentioned "IPS programming to get the bootloader" but I'm not sure where to start with this.
Sidenote: I should mention that when the halves are connected, there is a slight difference in the lighting/hue/colors of LED's between the halves for LED presets apart from a few. 

It is rather frustrating not being able to communicate with the pro micro's even though I was once able to... 

Anyone who can help with this problem is much appreciated.

**Comment by benomite** [comment]
Hi @Gazza2000 I think I am having a similar issue, did you manage to get your pro micros finally recognized by windows?
