### ISSUE TITLE
[Question] Flip the Pro Micro on right pad?

### ISSUE THREAD

**Issue by lamafab** [MakotoKurauchi/helix#28]
Hi

Quick question; does the Pro Micro need to be flipped on the right pad? Or can the bottom side also face upwards like on the left side?

Thanks a lot.

**Comment by mtei** [comment]
Do the following on either side:
![down](https://camo.githubusercontent.com/667a37b45c7eeef19cbd5c7c63f4c4e22c2acb78/68747470733a2f2f692e696d6775722e636f6d2f486a35594868702e6a7067)

**Comment by lamafab** [comment]
@mtei Perfect, thank you for the answer!
