### ISSUE TITLE
What keycaps are in the picture on the README?

### ISSUE THREAD

**Issue by damouse** [MakotoKurauchi/helix#30]
I'm sorry this is not a real issue-- I'm just enchanted with the keycaps shown in the picture. What keycaps are these? 

Thanks!

**Comment by MakotoKurauchi** [comment]
Hi

The keycaps used in the photo are sold below.
https://yushakobo.jp/shop/pg1350cap-blank/

**Comment by damouse** [comment]
Thanks!
