### ISSUE TITLE
Right side does not work

### ISSUE THREAD

**Issue by vbchekhov** [MakotoKurauchi/helix#33]
Hello, I collected everything, I asked for it, but the right side does not work, if I change the cable in places, the left side does not work. How do I fix the problem? I ran the firmware on both sides.

![image](https://user-images.githubusercontent.com/27843284/91127880-d4ad1680-e6af-11ea-8737-d88dd76757b5.png)

qmk setting 
![image](https://user-images.githubusercontent.com/27843284/91128623-33bf5b00-e6b1-11ea-9359-0999f303a53d.png)

**Comment by MakotoKurauchi** [comment]
Try these

Replace TRRS cable.
Check the soldering of the TRRS jack.
Check ProMicro soldering.

**Comment by vbchekhov** [comment]
_Replace TRRS cable._ Done, 100% worked.
soldering 
![image](https://user-images.githubusercontent.com/27843284/91155023-f49e0380-e6ca-11ea-833b-2242c5051516.png)

**Comment by vbchekhov** [comment]
TRPC cable needs mono or stereo? Could it be too long?

**Comment by MakotoKurauchi** [comment]
It looks like it's shorted out here
![91155023-f49e0380-e6ca-11ea-833b-2242c5051516](https://user-images.githubusercontent.com/4564996/91163554-b45d7600-e708-11ea-9cb0-241d98776efa.png)

**Comment by MakotoKurauchi** [comment]
This is also suspicious
![91155023-f49e0380-e6ca-11ea-833b-2242c5051516](https://user-images.githubusercontent.com/4564996/91163790-16b67680-e709-11ea-9aee-32a6a7f3d524.png)

**Comment by vbchekhov** [comment]
Yep, fixed all the problems and it worked!
